# cPanel Git Deployment Configuration
# Guide: https://docs.cpanel.net/knowledge-base/web-services/guide-to-git-deployment/

---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nocastra/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp Logo.png $DEPLOYPATH
    - /bin/cp Gemini_Generated_Image_fsrbdrfsrbdrfsrb.png $DEPLOYPATH
